version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
        environment:
          TYPEORM_CONNECTION: postgres
          TYPEORM_HOST: localhost
          TYPEORM_USERNAME: root
          TYPEORM_PASSWORD: localhost
          TYPEORM_DATABASE: circle_test
          TYPEORM_SYNCHRONIZE: true
          TYPEORM_ENTITIES: models/*.ts,../models/*.ts,./models/*.ts,/models/*.ts
          TYPEORM_ENTITIES_DIR: models/,../models/,./models/
          NODE_ENV: development

      - image: circleci/postgres:9.6.9-alpine

    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run: touch .env.testing
      - run: echo "TYPEORM_URL=${TYPEORM_URL}" >> .env.testing
      - run: sudo npm install

      - run: npm test
